# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    authentication_entry_point:
        class: AppBundle\Security\AuthenticationEntryPoint
        arguments: [ @router ]
    app.workout_import:
        class:  AppBundle\Service\WorkoutImportService
        arguments: ["@doctrine.orm.entity_manager", "@translator", "@=service('security.token_storage').getToken().getUser()"]
    security.access.workout_voter:
            class:      AppBundle\Security\Authorization\Voter\WorkoutVoter
            public:     false
            tags:
               - { name: security.voter }
    security.access.sport_voter:
           class:      AppBundle\Security\Authorization\Voter\SportVoter
           public:     false
           tags:
              - { name: security.voter }
    app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }